In [1]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
import pandas as pd
docs= pd.read_table('SMSSpamCollection+(1)', header=None, names=['Class', 'sms'])
import warnings
warnings.filterwarnings("ignore")

In [2]:
docs.shape

(5572, 2)

In [3]:
docs.head()

Class                                                sms
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
docs['sms'].head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: sms, dtype: object

In [5]:
docs['Class'].value_counts()

Class
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
docs['label'] = docs.Class.map({'ham': 0, 'spam': 1})

In [7]:
docs.head()

Class                                                sms  label
0   ham  Go until jurong point, crazy.. Available only ...      0
1   ham                      Ok lar... Joking wif u oni...      0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
3   ham  U dun say so early hor... U c already then say...      0
4   ham  Nah I don't think he goes to usf, he lives aro...      0

In [8]:
x = docs.sms
y = docs.label
print(x.shape, y.shape)

(5572,) (5572,)


In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.3, random_state=1)

In [10]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(3900,) (1672,) (3900,) (1672,)


In [11]:
x_train.head()

4393                       what are your new years plans?
216     Finally the match heading towards draw as your...
4471    Lemme know when I can swing by and pick up, I'...
3889                   ok....take care.umma to you too...
5030    I'd like to tell you my deepest darkest fantas...
Name: sms, dtype: object

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
data= ['the quick brown fox jumps over the lazy dog']
vectorizer = CountVectorizer()
vectorizer.fit(data)
print('given data:', data)
print("-"*20)
print('vocabulary:', vectorizer.vocabulary_)
print("-"*20)
vector = vectorizer.transform(data)
print(vector.shape)
print(type(vector))
print("-"*20)
print(vectorizer.get_feature_names_out())
print(vector.toarray())

given data: ['the quick brown fox jumps over the lazy dog']
--------------------
vocabulary: {'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumps': 3, 'over': 5, 'lazy': 4, 'dog': 1}
--------------------
(1, 8)
<class 'scipy.sparse._csr.csr_matrix'>
--------------------
['brown' 'dog' 'fox' 'jumps' 'lazy' 'over' 'quick' 'the']
[[1 1 1 1 1 1 1 2]]


In [13]:
data1 = ["the king brown fox"]
vector= vectorizer.transform(data1)
print(vector.shape)
print(vector.toarray())
print(vectorizer.get_feature_names_out())

(1, 8)
[[1 0 1 0 0 0 0 1]]
['brown' 'dog' 'fox' 'jumps' 'lazy' 'over' 'quick' 'the']


In [14]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\skakt\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [15]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
print(stop_words)
print(len(stop_words))
type(stop_words)

{'has', 'the', "aren't", 'before', 'being', 'own', "we've", 'who', 'again', "shan't", 'ain', 'so', "you'll", 'mustn', "she'll", 'what', 'against', 'shan', 'wouldn', 'he', 'weren', 're', 'hers', 'do', "that'll", 'which', 'few', 'by', "shouldn't", 'a', "it's", "wasn't", "she'd", 'once', 'didn', 'those', 'isn', "i'm", "doesn't", 'these', 'now', 'down', 'will', 'does', 'o', 'only', 'just', 'or', 'very', "you've", "won't", 'yourselves', 'at', "hasn't", 'when', 'while', 'should', 'it', 'each', 'from', 'any', 'doesn', 'its', 'an', 'ma', 'into', "isn't", 'until', "hadn't", "he'd", 'shouldn', "we'd", 'couldn', "we'll", 'as', "mightn't", "mustn't", 'all', 'both', 'for', 'having', 'most', "you'd", "needn't", 'between', 'but', "i've", 'this', 'then', 'about', 'her', 'over', 'off', 'such', 'hasn', "didn't", "they're", 'yours', 'nor', 'not', 'him', "should've", 'than', 'your', 've', 'same', 'too', 'above', "they've", 'through', "they'll", 'under', 'how', 'whom', "i'd", 'myself', 'other', 'if', 'to',

set

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(stop_words='english')
vect.fit(x_train)

CountVectorizer(stop_words='english')

In [17]:
vect.vocabulary_

{'new': 4272,
 'years': 6855,
 'plans': 4682,
 'finally': 2550,
 'match': 3930,
 'heading': 3018,
 'draw': 2202,
 'prediction': 4801,
 'lemme': 3650,
 'know': 3548,
 'swing': 5957,
 'pick': 4644,
 'free': 2663,
 'basically': 1119,
 'time': 6163,
 'semester': 5369,
 'ok': 4406,
 'care': 1485,
 'umma': 6353,
 'like': 3685,
 'tell': 6043,
 'deepest': 2000,
 'darkest': 1949,
 'fantasies': 2478,
 '09094646631': 222,
 'just': 3472,
 '60p': 538,
 'min': 4022,
 'stop': 5804,
 'texts': 6083,
 '08712460324': 103,
 'nat': 4218,
 'rate': 4985,
 'lmao': 3732,
 'fish': 2566,
 'memory': 3984,
 'need': 4243,
 'yahoo': 6841,
 'boys': 1324,
 'bring': 1354,
 'perf': 4592,
 'legal': 3644,
 'hiya': 3083,
 'comin': 1722,
 'bristol': 1358,
 'st': 5740,
 'week': 6637,
 'april': 940,
 'les': 3656,
 'got': 2862,
 'rudi': 5234,
 'yrs': 6882,
 'eve': 2383,
 'snoring': 5603,
 'drunk': 2226,
 'bak': 1092,
 'college': 1710,
 'work': 6769,
 'sends': 5374,
 'ink': 3289,
 'bath': 1123,
 'wamma': 6574,
 'laid': 3581,
 '

In [18]:
vect.get_feature_names_out()

array(['00', '000', '008704050406', '0121', '01223585236', '01223585334',
       '0125698789', '02', '0207', '02072069400', '02073162414',
       '02085076972', '021', '03', '04', '0430', '05', '050703', '0578',
       '06', '07', '07008009200', '07090201529', '07123456789',
       '07732584351', '07734396839', '07742676969', '0776xxxxxxx',
       '07781482378', '07786200117', '078', '07801543489', '07808',
       '07808247860', '07808726822', '07815296484', '07821230901',
       '0789xxxxxxx', '0796xxxxxx', '07973788240', '07xxxxxxxxx', '08',
       '0800', '08000407165', '08000776320', '08000839402', '08000930705',
       '08000938767', '08001950382', '08002888812', '08002986030',
       '08002986906', '08002988890', '08006344447', '0808', '08081263000',
       '08081560665', '0825', '083', '0844', '08448714184', '0845',
       '08450542832', '08452810071', '08452810073', '08452810075over18',
       '0870', '08700435505150p', '08700469649', '08700621170150p',
       '08701213186', '0

In [19]:
x_train_tran = vect.transform(x_train)
x_test_tran = vect.transform(x_test)

In [20]:
type(x_train_tran)

scipy.sparse._csr.csr_matrix

In [21]:
print(x_train_tran.shape)

(3900, 6904)


In [22]:
print(x_train_tran[1, :].toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [23]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(x_train_tran, y_train)
y_pred_class = bnb.predict(x_test_tran[1, :].toarray())
print(y_pred_class)

[0]


In [24]:
from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(x_train_tran, y_train)
y_pred_class = bnb.predict(x_test_tran)
print(y_pred_class)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1
 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0
 0 0 0 0 0 0 1 0 0 1 0 0 

In [25]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.9730861244019139

In [26]:
bnb

BernoulliNB()

In [27]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[1441,    1],
       [  44,  186]])

In [28]:
confusion = metrics.confusion_matrix(y_test, y_pred_class)
print(confusion)
tn = confusion[0, 0]
fp = confusion[0, 1]
fn = confusion[1, 0]
tp = confusion[1, 1]

[[1441    1]
 [  44  186]]


In [29]:
sensitivity = tp / float(tp + fn)
print("Sensitivity:", sensitivity)

Sensitivity: 0.808695652173913


In [30]:
specificity = tn / float(tn + fp)
print("Specificity:", specificity)

Specificity: 0.9993065187239945


In [31]:
precision = tp / float(tp + fp)
print("Precision:", precision)
print(metrics.precision_score(y_test, y_pred_class))

Precision: 0.9946524064171123
0.9946524064171123


In [32]:
print("Recall:", metrics.recall_score(y_test, y_pred_class))
print("F1 Score:", metrics.f1_score(y_test, y_pred_class))
print("precision:", metrics.precision_score(y_test, y_pred_class))

Recall: 0.808695652173913
F1 Score: 0.8920863309352518
precision: 0.9946524064171123


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred_class))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1442
           1       0.99      0.81      0.89       230

    accuracy                           0.97      1672
   macro avg       0.98      0.90      0.94      1672
weighted avg       0.97      0.97      0.97      1672

